---
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable         # enable new upcoming cops for rubocop

  # ignore block length where unavoidable (e.g., framework requires it)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'Rakefile' # Rake namespaces produce large blocks
    - app/controllers/* # Roda's nested controllers require large blocks
    - spec/**/* # Minitest's nested test structure requires large blocks
