---
<%= ENV['RACK_ENV'] %>:
  DATABASE_URL: <%= "sqlite://app/db/store/#{ENV['RACK_ENV']}.db" %>
  DB_KEY: <%= SecureDB.generate_key %>
  SECURE_SCHEME: HTTP

production:
  DATABASE_URL: <%= ENV['DATABASE_URL'] %>
  DB_KEY: <%= ENV['DB_KEY'] %>
  SECURE_SCHEME: HTTPS
