---
<%= ENV['RACK_ENV'] %>:
  DATABASE_URL: <%= "sqlite://app/db/store/#{ENV['RACK_ENV']}.db" %>
  DB_KEY: <%= SecureDB.generate_key %>
  MSG_KEY: <%= AuthToken.generate_key %>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: <%= ENV['SENDGRID_API_KEY'] %>
  SENDGRID_FROM_EMAIL: <%= ENV['SENDGRID_FROM_EMAIL'] %>
  SECURE_SCHEME: HTTP

production:
  DB_KEY: <%= SecureDB.generate_key %>
  MSG_KEY: <%= AuthToken.generate_key %>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_API_KEY: <%= ENV['SENDGRID_API_KEY'] %>
  SENDGRID_FROM_EMAIL: <%= ENV['SENDGRID_FROM_EMAIL'] %>
  SECURE_SCHEME: HTTPS
