---
development:
  DB_KEY: 'H6KIqhXEMO1Ypy8fTWI3DP+5VlCWbO5ubODE4//I+3Q='
  DATABASE_URL: sqlite://app/db/store/development.db

  test:
    DB_KEY: 'f9cf0s9JF1vuu8Z9mqAGigkviESWIa8mBEflgz9U9Zg='
    DATABASE_URL: sqlite://app/db/store/test.db
